var friendsAge=[15,16,17,18];
var sonali=friendsAge[2];
friendsAge[0]=21;
var position=friendsAge.indexOf(16);
console.log(friendsAge);
console.log(friendsAge.length);
friendsAge.push(19);
friendsAge.push(18);
console.log(friendsAge);
console.log(friendsAge.length);
friendsAge.pop();
console.log(friendsAge);
console.log(friendsAge.length);
friendsAge.shift();
console.log(friendsAge);
console.log(friendsAge.length);
friendsAge.unshift(13);
console.log(friendsAge);
console.log(friendsAge.length);